# Generated by Django 5.0.6 on 2024-07-03 09:42

import authentication.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(default=authentication.models.get_ist_datetime),
        ),
    ]
